
name: tin
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - black
    - neovim
    - nbval
    - pip-chill
    - pytest
    - pytest-cov
    - pytest-subtests
    - pep517
    - twine
    - -r file:requirements.txt

